/**
 * Generate icon map from SVG files in DS1/x-icon/
 *
 * This script reads all SVG files and generates a TypeScript module
 * that exports a static map of icon names to SVG strings.
 *
 * Run: bun run scripts/generate-icons.ts
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join, basename } from "path";

const ICONS_DIR = join(import.meta.dir, "..", "DS1", "x-icon");
const OUTPUT_DIR = join(import.meta.dir, "..", "DS1", "2-core", "generated");
const OUTPUT_FILE = join(OUTPUT_DIR, "ds-icon-map.ts");

function generateIconMap() {
  // Ensure output directory exists
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Read all SVG files
  const svgFiles = readdirSync(ICONS_DIR).filter((file) =>
    file.toLowerCase().endsWith(".svg")
  );

  // Build the map
  const iconMap: Record<string, string> = {};

  for (const file of svgFiles) {
    const filePath = join(ICONS_DIR, file);
    const iconName = basename(file, ".svg").toLowerCase();
    const svgContent = readFileSync(filePath, "utf-8").trim();
    iconMap[iconName] = svgContent;
  }

  // Sort keys for consistent output
  const sortedKeys = Object.keys(iconMap).sort();

  // Generate TypeScript content
  const tsContent = `/**
 * Auto-generated icon map - DO NOT EDIT
 * Generated by: bun run scripts/generate-icons.ts
 * Source: DS1/x-icon/*.svg
 */

export const iconNameToSvgMap: Record<string, string> = {
${sortedKeys.map((key) => `  "${key}": ${JSON.stringify(iconMap[key])},`).join("\n")}
};

export type IconName = keyof typeof iconNameToSvgMap;

export const iconNames = [
${sortedKeys.map((key) => `  "${key}",`).join("\n")}
] as const;
`;

  writeFileSync(OUTPUT_FILE, tsContent, "utf-8");

  console.log(`✓ Generated ${OUTPUT_FILE}`);
  console.log(`  ${sortedKeys.length} icons: ${sortedKeys.join(", ")}`);
}

generateIconMap();


